import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next/Bootstrap App </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-primary text-center">Hello World</h1>
      </main>
    </>
  );
}
